version: '3.8'

services:
  steam-api:
    build: .
    container_name: steam-api-explorer
    restart: unless-stopped
    ports:
      - "3008:3008"
    volumes:
      - ./.env.local:/usr/src/app/.env.local
    environment:
      - NODE_ENV=production
      - PORT=3008
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3008"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s 