version: '3.8'

services:
  steam-api:
    build: .
    container_name: steam-api-explorer
    restart: unless-stopped
    ports:
      - "3008:3008"
    env_file:
      - .env.local  # Only used for local development
    environment:
      - NODE_ENV=${NODE_ENV}  # Automatically takes the value from .env.local or Railway
      - PORT=${PORT}
      - API_KEY=${API_KEY}  # Value injected by Railway in production
      - HM_STEAM_ID=${HM_STEAM_ID}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3008"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
